---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Hot:
    - Proxmox:
        href: {{HOMEPAGE_VAR_PVE_URL}}
        icon: proxmox.png
        description: {{HOMEPAGE_VAR_PVE_URL}}
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PVE_URL}}
            username: {{HOMEPAGE_VAR_PVE_USERNAME}}
            password: {{HOMEPAGE_VAR_PVE_PASSWORD}}

    - Immich: 
        href: {{HOMEPAGE_VAR_IMMICH_URL}}
        icon: immich.png
        description: Immich Self-hosted photo and video backup solution
        widget:
            type: immich
            url: {{HOMEPAGE_VAR_IMMICH_URL}}
            key: {{HOMEPAGE_VAR_IMMICH_API_KEY}}
            fields: ["photos", "videos", "storage"]

    - Adguard:
        href: {{HOMEPAGE_VAR_ADGUARD_URL}}
        icon: adguard-home.png
        description: DNS server that blocks ads and trackers on all your devices within your network.
        widget:
            type: adguard
            url: {{HOMEPAGE_VAR_ADGUARD_URL}}
            username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
            password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
            fields: ["queries", "blocked", "latency"]

- Media:

    - Overseerr:
        href: {{HOMEPAGE_VAR_OVERSEERR_URL}}
        icon: overseerr.png
        description: It helps you find and request media for your Plex server
        widget:
            type: overseerr
            url: {{HOMEPAGE_VAR_OVERSEERR_URL}}
            fields: ["pending", "approved", "available", "processing"]
            key: {{HOMEPAGE_VAR_OVERSEERR_API_KEY}}

    - Deluge:
        href: {{HOMEPAGE_VAR_DELUGE_URL}}
        icon: deluge.png
        description: Free and open-source, BitTorrent client written in Python.
        widget:
            type: deluge
            url: {{HOMEPAGE_VAR_DELUGE_URL}}
            password: {{HOMEPAGE_VAR_DELUGE_PASSWORD}} 

    - Plex:
        href: {{HOMEPAGE_VAR_PLEX_PUBLIC_URL}}
        icon: plex.png
        description: Plex
        widget:
            type: plex
            url: {{HOMEPAGE_VAR_PLEX_URL}}
            key: {{HOMEPAGE_VAR_PLEX_API_KEY}} 
            fields: ["streams", "movies", "tv"]

    - SpeedTest:
        href: {{HOMEPAGE_VAR_SPEEDTEST_URL}}
        icon: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}/img/speedtest-tracker-icon.png"
        description: Self-hosted internet performance tracking application
        widget:
            type: speedtest
            url: {{HOMEPAGE_VAR_SPEEDTEST_URL}}
            bitratePrecision: 3 
            fields: ["download", "upload"]
    
    - Home Assistant:
        href: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
        icon: home-assistant.png
        description: Versatile and trustworthy smart home hub that works with over 1000 brands and integrations.
        widget:
            type: homeassistant
            url: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
            key: {{HOMEPAGE_VAR_HOMEASSISTANT_API_KEY}}
            custom:
                - state: sensor.knight_energy_cost
                  label: Energy Cost

                - state: sensor.arkhamknight_current_power
                  label: Current Power

- Information:
    - Calendar:
        widget:
            type: calendar
            firstDayInWeek: monday
            view: monthly 
            maxEvents: 10
            showTime: true 
            timezone: {{HOMEPAGE_VAR_CALENDAR_TIMEZONE}}
            integrations:
                - type: ical 
                  url: {{HOMEPAGE_VAR_CALENDAR_ICS}}
                  name: Event
                  color: blue 
                  params: 
                    showName: true
