name: Update and Restart Docker

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  update-docker:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Import Secrets
      uses: hashicorp/vault-action@v2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        tlsSkipVerify: true
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          kv/data/homepage HOMEPAGE_VAR_PVE_URL | HOMEPAGE_VAR_PVE_URL ;
          kv/data/homepage HOMEPAGE_VAR_PVE_USERNAME | HOMEPAGE_VAR_PVE_USERNAME ;
          kv/data/homepage HOMEPAGE_VAR_PVE_PASSWORD | HOMEPAGE_VAR_PVE_PASSWORD ;
          kv/data/homepage HOMEPAGE_VAR_IMMICH_URL | HOMEPAGE_VAR_IMMICH_URL ;
          kv/data/homepage HOMEPAGE_VAR_IMMICH_API_KEY | HOMEPAGE_VAR_IMMICH_API_KEY ;
          kv/data/homepage HOMEPAGE_VAR_ADGUARD_URL | HOMEPAGE_VAR_ADGUARD_URL ;
          kv/data/homepage HOMEPAGE_VAR_ADGUARD_USERNAME | HOMEPAGE_VAR_ADGUARD_USERNAME ;
          kv/data/homepage HOMEPAGE_VAR_ADGUARD_PASSWORD | HOMEPAGE_VAR_ADGUARD_PASSWORD ;
          kv/data/homepage HOMEPAGE_VAR_OVERSEERR_URL | HOMEPAGE_VAR_OVERSEERR_URL ;
          kv/data/homepage HOMEPAGE_VAR_OVERSEERR_API_KEY | HOMEPAGE_VAR_OVERSEERR_API_KEY ;
          kv/data/homepage HOMEPAGE_VAR_DELUGE_URL | HOMEPAGE_VAR_DELUGE_URL ;
          kv/data/homepage HOMEPAGE_VAR_DELUGE_PASSWORD | HOMEPAGE_VAR_DELUGE_PASSWORD ;
          kv/data/homepage HOMEPAGE_VAR_PLEX_PUBLIC_URL | HOMEPAGE_VAR_PLEX_PUBLIC_URL ;
          kv/data/homepage HOMEPAGE_VAR_PLEX_URL | HOMEPAGE_VAR_PLEX_URL ;
          kv/data/homepage HOMEPAGE_VAR_PLEX_API_KEY | HOMEPAGE_VAR_PLEX_API_KEY ;
          kv/data/homepage HOMEPAGE_VAR_SPEEDTEST_URL | HOMEPAGE_VAR_SPEEDTEST_URL ;
          kv/data/homepage HOMEPAGE_VAR_HOMEASSISTANT_URL | HOMEPAGE_VAR_HOMEASSISTANT_URL ;
          kv/data/homepage HOMEPAGE_VAR_HOMEASSISTANT_API_KEY | HOMEPAGE_VAR_HOMEASSISTANT_API_KEY ;
          kv/data/homepage HOMEPAGE_VAR_CALENDAR_TIMEZONE | HOMEPAGE_VAR_CALENDAR_TIMEZONE ;
          kv/data/homepage HOMEPAGE_VAR_CALENDAR_ICS | HOMEPAGE_VAR_CALENDAR_ICS ;

    - name: 'Create .env file'
      run: |
          touch /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_PVE_URL=${{ env.HOMEPAGE_VAR_PVE_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_PVE_USERNAME=${{ env.HOMEPAGE_VAR_PVE_USERNAME }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_PVE_PASSWORD=${{ env.HOMEPAGE_VAR_PVE_PASSWORD }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_IMMICH_URL=${{ env.HOMEPAGE_VAR_IMMICH_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_IMMICH_API_KEY=${{ env.HOMEPAGE_VAR_IMMICH_API_KEY }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_ADGUARD_URL=${{ env.HOMEPAGE_VAR_ADGUARD_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_ADGUARD_USERNAME=${{ env.HOMEPAGE_VAR_ADGUARD_USERNAME }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_ADGUARD_PASSWORD=${{ env.HOMEPAGE_VAR_ADGUARD_PASSWORD }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_OVERSEERR_URL=${{ env.HOMEPAGE_VAR_OVERSEERR_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_OVERSEERR_API_KEY=${{ env.HOMEPAGE_VAR_OVERSEERR_API_KEY }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_DELUGE_URL=${{ env.HOMEPAGE_VAR_DELUGE_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_DELUGE_PASSWORD=${{ env.HOMEPAGE_VAR_DELUGE_PASSWORD }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_PLEX_PUBLIC_URL=${{ env.HOMEPAGE_VAR_PLEX_PUBLIC_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_PLEX_URL=${{ env.HOMEPAGE_VAR_PLEX_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_PLEX_API_KEY=${{ env.HOMEPAGE_VAR_PLEX_API_KEY }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_SPEEDTEST_URL=${{ env.HOMEPAGE_VAR_SPEEDTEST_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_HOMEASSISTANT_URL=${{ env.HOMEPAGE_VAR_HOMEASSISTANT_URL }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_HOMEASSISTANT_API_KEY=${{ env.HOMEPAGE_VAR_HOMEASSISTANT_API_KEY }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_CALENDAR_TIMEZONE=${{ env.HOMEPAGE_VAR_CALENDAR_TIMEZONE }}" >> /home/gitrunner/homepage/.env
          echo "envkey_HOMEPAGE_VAR_CALENDAR_ICS=${{ env.HOMEPAGE_VAR_CALENDAR_ICS }}" >> /home/gitrunner/homepage/.env
          cat /home/gitrunner/homepage/.env
        
        

    - name: Pull latest changes and restart Docker
      run: |
        echo "PVE URL is $HOMEPAGE_VAR_PVE_URL"

        # Define your project directory and Docker compose file
        PROJECT_DIR="/home/gitrunner/homepage"
        DOCKER_COMPOSE_FILE="docker-compose.yml"

        # Navigate to the project directory
        cd $PROJECT_DIR

        # Pull the latest changes from the GitHub repository
        git pull origin main

        docker compose down
        docker compose up -d
