name: Update and Restart Docker

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  update-docker:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Import Secrets
      uses: hashicorp/vault-action@v2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        tlsSkipVerify: true
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          secrets/kv/homepage HOMEPAGE_VAR_PVE_URL | HOMEPAGE_VAR_PVE_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_PVE_USERNAME | HOMEPAGE_VAR_PVE_USERNAME ;
          secrets/kv/homepage HOMEPAGE_VAR_PVE_PASSWORD | HOMEPAGE_VAR_PVE_PASSWORD ;
          secrets/kv/homepage HOMEPAGE_VAR_IMMICH_URL | HOMEPAGE_VAR_IMMICH_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_IMMICH_API_KEY | HOMEPAGE_VAR_IMMICH_API_KEY ;
          secrets/kv/homepage HOMEPAGE_VAR_ADGUARD_URL | HOMEPAGE_VAR_ADGUARD_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_ADGUARD_USERNAME | HOMEPAGE_VAR_ADGUARD_USERNAME ;
          secrets/kv/homepage HOMEPAGE_VAR_ADGUARD_PASSWORD | HOMEPAGE_VAR_ADGUARD_PASSWORD ;
          secrets/kv/homepage HOMEPAGE_VAR_OVERSEERR_URL | HOMEPAGE_VAR_OVERSEERR_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_OVERSEERR_API_KEY | HOMEPAGE_VAR_OVERSEERR_API_KEY ;
          secrets/kv/homepage HOMEPAGE_VAR_DELUGE_URL | HOMEPAGE_VAR_DELUGE_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_DELUGE_PASSWORD | HOMEPAGE_VAR_DELUGE_PASSWORD ;
          secrets/kv/homepage HOMEPAGE_VAR_PLEX_PUBLIC_URL | HOMEPAGE_VAR_PLEX_PUBLIC_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_PLEX_URL | HOMEPAGE_VAR_PLEX_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_PLEX_API_KEY | HOMEPAGE_VAR_PLEX_API_KEY ;
          secrets/kv/homepage HOMEPAGE_VAR_SPEEDTEST_URL | HOMEPAGE_VAR_SPEEDTEST_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_HOMEASSISTANT_URL | HOMEPAGE_VAR_HOMEASSISTANT_URL ;
          secrets/kv/homepage HOMEPAGE_VAR_HOMEASSISTANT_API_KEY | HOMEPAGE_VAR_HOMEASSISTANT_API_KEY ;
          secrets/kv/homepage HOMEPAGE_VAR_CALENDAR_TIMEZONE | HOMEPAGE_VAR_CALENDAR_TIMEZONE ;
          secrets/kv/homepage HOMEPAGE_VAR_CALENDAR_ICS | HOMEPAGE_VAR_CALENDAR_ICS ;
    
    
    
        

    - name: Pull latest changes and restart Docker
      run: |
        # Define your project directory and Docker compose file
        PROJECT_DIR="/home/gitrunner/homepage"
        DOCKER_COMPOSE_FILE="docker-compose.yml"

        # Navigate to the project directory
        cd $PROJECT_DIR

        # Pull the latest changes from the GitHub repository
        git pull origin main

        docker compose down
        docker compose up -d
