name: Update and Restart Docker

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  update-docker:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Import Secrets
      uses: hashicorp/vault-action@v2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        tlsSkipVerify: true
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          /v1/kv/data/homepage HOMEPAGE_VAR_PVE_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_PVE_USERNAME
          /v1/kv/data/homepage HOMEPAGE_VAR_PVE_PASSWORD
          /v1/kv/data/homepage HOMEPAGE_VAR_IMMICH_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_IMMICH_API_KEY
          /v1/kv/data/homepage HOMEPAGE_VAR_ADGUARD_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_ADGUARD_USERNAME
          /v1/kv/data/homepage HOMEPAGE_VAR_ADGUARD_PASSWORD
          /v1/kv/data/homepage HOMEPAGE_VAR_OVERSEERR_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_OVERSEERR_API_KEY
          /v1/kv/data/homepage HOMEPAGE_VAR_DELUGE_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_DELUGE_PASSWORD
          /v1/kv/data/homepage HOMEPAGE_VAR_PLEX_PUBLIC_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_PLEX_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_PLEX_API_KEY
          /v1/kv/data/homepage HOMEPAGE_VAR_SPEEDTEST_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_HOMEASSISTANT_URL
          /v1/kv/data/homepage HOMEPAGE_VAR_HOMEASSISTANT_API_KEY
          /v1/kv/data/homepage HOMEPAGE_VAR_CALENDAR_TIMEZONE
          /v1/kv/data/homepage HOMEPAGE_VAR_CALENDAR_ICS
    
    - name: Import Secrets
      uses: hashicorp/vault-action@v2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        tlsSkipVerify: true
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          kv/data/homepage HOMEPAGE_VAR_PVE_URL | HOMEPAGE_VAR_PVE_URL
          kv/data/homepage HOMEPAGE_VAR_PVE_USERNAME | HOMEPAGE_VAR_PVE_USERNAME
          kv/data/homepage HOMEPAGE_VAR_PVE_PASSWORD | HOMEPAGE_VAR_PVE_PASSWORD
          kv/data/homepage HOMEPAGE_VAR_IMMICH_URL | HOMEPAGE_VAR_IMMICH_URL
          kv/data/homepage HOMEPAGE_VAR_IMMICH_API_KEY | HOMEPAGE_VAR_IMMICH_API_KEY
          kv/data/homepage HOMEPAGE_VAR_ADGUARD_URL | HOMEPAGE_VAR_ADGUARD_URL
          kv/data/homepage HOMEPAGE_VAR_ADGUARD_USERNAME | HOMEPAGE_VAR_ADGUARD_USERNAME
          kv/data/homepage HOMEPAGE_VAR_ADGUARD_PASSWORD | HOMEPAGE_VAR_ADGUARD_PASSWORD
          kv/data/homepage HOMEPAGE_VAR_OVERSEERR_URL | HOMEPAGE_VAR_OVERSEERR_URL
          kv/data/homepage HOMEPAGE_VAR_OVERSEERR_API_KEY | HOMEPAGE_VAR_OVERSEERR_API_KEY
          kv/data/homepage HOMEPAGE_VAR_DELUGE_URL | HOMEPAGE_VAR_DELUGE_URL
          kv/data/homepage HOMEPAGE_VAR_DELUGE_PASSWORD | HOMEPAGE_VAR_DELUGE_PASSWORD
          kv/data/homepage HOMEPAGE_VAR_PLEX_PUBLIC_URL | HOMEPAGE_VAR_PLEX_PUBLIC_URL
          kv/data/homepage HOMEPAGE_VAR_PLEX_URL | HOMEPAGE_VAR_PLEX_URL
          kv/data/homepage HOMEPAGE_VAR_PLEX_API_KEY | HOMEPAGE_VAR_PLEX_API_KEY
          kv/data/homepage HOMEPAGE_VAR_SPEEDTEST_URL | HOMEPAGE_VAR_SPEEDTEST_URL
          kv/data/homepage HOMEPAGE_VAR_HOMEASSISTANT_URL | HOMEPAGE_VAR_HOMEASSISTANT_URL
          kv/data/homepage HOMEPAGE_VAR_HOMEASSISTANT_API_KEY | HOMEPAGE_VAR_HOMEASSISTANT_API_KEY
          kv/data/homepage HOMEPAGE_VAR_CALENDAR_TIMEZONE | HOMEPAGE_VAR_CALENDAR_TIMEZONE
          kv/data/homepage HOMEPAGE_VAR_CALENDAR_ICS | HOMEPAGE_VAR_CALENDAR_ICS
        

    - name: Pull latest changes and restart Docker
      run: |
        # Define your project directory and Docker compose file
        PROJECT_DIR="/home/gitrunner/homepage"
        DOCKER_COMPOSE_FILE="docker-compose.yml"

        # Navigate to the project directory
        cd $PROJECT_DIR

        # Pull the latest changes from the GitHub repository
        git pull origin main

        docker compose down
        docker compose up -d
